/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7p2_victorcurz;

/**
 *
 * @author Victor Jafet Cruz
 */
public class Lab7P2_VictorCruz extends javax.swing.JFrame {

    /**
     * Creates new form LabP2_VictorCruz
     */
    public Lab7P2_VictorCruz() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JD_CRUDArstistas = new javax.swing.JDialog();
        JD_CRUDCanciones = new javax.swing.JDialog();
        JD_CRUDAlbumes = new javax.swing.JDialog();
        JD_Simulacion = new javax.swing.JDialog();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMI_CRUDArtista = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        JMI_CRUDCanciones = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        JMI_CRUDAlbumes = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        JMI_SimulacionRepdructor = new javax.swing.JMenuItem();

        javax.swing.GroupLayout JD_CRUDArstistasLayout = new javax.swing.GroupLayout(JD_CRUDArstistas.getContentPane());
        JD_CRUDArstistas.getContentPane().setLayout(JD_CRUDArstistasLayout);
        JD_CRUDArstistasLayout.setHorizontalGroup(
            JD_CRUDArstistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        JD_CRUDArstistasLayout.setVerticalGroup(
            JD_CRUDArstistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JD_CRUDCancionesLayout = new javax.swing.GroupLayout(JD_CRUDCanciones.getContentPane());
        JD_CRUDCanciones.getContentPane().setLayout(JD_CRUDCancionesLayout);
        JD_CRUDCancionesLayout.setHorizontalGroup(
            JD_CRUDCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        JD_CRUDCancionesLayout.setVerticalGroup(
            JD_CRUDCancionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JD_CRUDAlbumesLayout = new javax.swing.GroupLayout(JD_CRUDAlbumes.getContentPane());
        JD_CRUDAlbumes.getContentPane().setLayout(JD_CRUDAlbumesLayout);
        JD_CRUDAlbumesLayout.setHorizontalGroup(
            JD_CRUDAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        JD_CRUDAlbumesLayout.setVerticalGroup(
            JD_CRUDAlbumesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JD_SimulacionLayout = new javax.swing.GroupLayout(JD_Simulacion.getContentPane());
        JD_Simulacion.getContentPane().setLayout(JD_SimulacionLayout);
        JD_SimulacionLayout.setHorizontalGroup(
            JD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        JD_SimulacionLayout.setVerticalGroup(
            JD_SimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jButton1.setText("Salir del Sistema");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jToolBar1.add(jButton1);

        jMenu1.setText("Artistas");

        JMI_CRUDArtista.setText("CRUD Artistas");
        JMI_CRUDArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_CRUDArtistaActionPerformed(evt);
            }
        });
        jMenu1.add(JMI_CRUDArtista);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Canciones");

        JMI_CRUDCanciones.setText("CRUD Canciones");
        JMI_CRUDCanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_CRUDCancionesActionPerformed(evt);
            }
        });
        jMenu2.add(JMI_CRUDCanciones);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Albumes");

        JMI_CRUDAlbumes.setText("CRUD Albumes");
        JMI_CRUDAlbumes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_CRUDAlbumesActionPerformed(evt);
            }
        });
        jMenu3.add(JMI_CRUDAlbumes);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Reproductor");

        JMI_SimulacionRepdructor.setText("Simulacion Reproductor");
        JMI_SimulacionRepdructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMI_SimulacionRepdructorActionPerformed(evt);
            }
        });
        jMenu4.add(JMI_SimulacionRepdructor);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 536, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 489, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMI_CRUDArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_CRUDArtistaActionPerformed
        Artistas();
    }//GEN-LAST:event_JMI_CRUDArtistaActionPerformed

    private void JMI_CRUDCancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_CRUDCancionesActionPerformed
      Canciones();
    }//GEN-LAST:event_JMI_CRUDCancionesActionPerformed

    private void JMI_CRUDAlbumesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_CRUDAlbumesActionPerformed
        // TODO add your handling code here:
        Albumes();
    }//GEN-LAST:event_JMI_CRUDAlbumesActionPerformed

    private void JMI_SimulacionRepdructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMI_SimulacionRepdructorActionPerformed
        // TODO add your handling code here:
        Simulacion();
    }//GEN-LAST:event_JMI_SimulacionRepdructorActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1MouseClicked

     public void Artistas(){
        JD_CRUDArstistas.pack();
        JD_CRUDArstistas.setModal(true);
        JD_CRUDArstistas.setLocationRelativeTo(this);
        JD_CRUDArstistas.setVisible(true);
    }
     
     public void Albumes(){
        JD_CRUDAlbumes.pack();
        JD_CRUDAlbumes.setModal(true);
        JD_CRUDAlbumes.setLocationRelativeTo(this);
        JD_CRUDAlbumes.setVisible(true);
    }
     
     public void Canciones(){
        JD_CRUDCanciones.pack();
        JD_CRUDCanciones.setModal(true);
        JD_CRUDCanciones.setLocationRelativeTo(this);
        JD_CRUDCanciones.setVisible(true);
    }
     public void Simulacion(){
        JD_Simulacion.pack();
        JD_Simulacion.setModal(true);
        JD_Simulacion.setLocationRelativeTo(this);
        JD_Simulacion.setVisible(true);
    }
     
     
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab7P2_VictorCruz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab7P2_VictorCruz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab7P2_VictorCruz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab7P2_VictorCruz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab7P2_VictorCruz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog JD_CRUDAlbumes;
    private javax.swing.JDialog JD_CRUDArstistas;
    private javax.swing.JDialog JD_CRUDCanciones;
    private javax.swing.JDialog JD_Simulacion;
    private javax.swing.JMenuItem JMI_CRUDAlbumes;
    private javax.swing.JMenuItem JMI_CRUDArtista;
    private javax.swing.JMenuItem JMI_CRUDCanciones;
    private javax.swing.JMenuItem JMI_SimulacionRepdructor;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
